### ISSUE TITLE
When the agent responds to an error, the program crashes.

### ISSUE THREAD

**Issue by FishOrBear** [TooTallNate/node-socks-proxy-agent#24]
Log:
```
Error: socket hang up
source-map-support.js:445
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

System:Window10  
Node:10  

Appropriate error handling should be added.

**Comment by FishOrBear** [comment]
```
        let request = http.get(opts, function (resx)
        {
            if (resx.statusCode === 200)
                res(new Date().getTime() - t1);
            else
                res(Infinity);
        });

        request.on("error", () =>
        {
            console.log("å‡ºé”™");
            res(Infinity);
        });
```
It might solve the problem.
