### ISSUE TITLE
FetchError: maximum redirect reached

### ISSUE THREAD

**Issue by esd23** [TooTallNate/node-socks-proxy-agent#47]
I've got the following exception when I try to fetch data from the [pornhub api](https://www.pornhub.com/webmasters/video_by_id?id=ph5c6a26be4c538&thumbsize=medium_hd)
````
FetchError: maximum redirect reached at: https://www.pornhub.com/webmasters/video_by_id?id=ph5c6a26be4c538&thumbsize=medium_hd
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1498:15)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:585:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:454:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:325:12)
    at readableAddChunk (_stream_readable.js:300:11)
    at TLSSocket.Readable.push (_stream_readable.js:234:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  message: 'maximum redirect reached at: https://www.pornhub.com/webmasters/video_by_id?id=ph5c6a26be4c538&thumbsize=medium_hd',
  type: 'max-redirect'
}
````

Does anyone have an idea whats happening there? I've tried the same proxy within my browser and everything is working normal. 
And yes, I've tested if I'm connected through the proxy …

**Comment by TooTallNate** [comment]
I can't seem to reproduce. Can you show some example code of how to demonstrate the issue?
