### ISSUE TITLE
TLS error isn't handled

### ISSUE THREAD

**Issue by ghost** [TooTallNate/node-socks-proxy-agent#53]
Please add handling of error in tls and soket connection:
**Client network socket disconnected before secure TLS connection was established**
Thank you

**Comment by fivemru** [comment]
There is a memory leak in the library. Not all errors are processed.

I have put the handler:

```
process.on('uncaughtException', (err) =>
  console.log('MY.uncaughtException', err),
);
```

and in my proxy checker I get a bunch of errors after the checker has finished working:

```
MY.uncaughtException Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
MY.uncaughtException Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:610:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1546:19)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: undefined,
  port: undefined,
  localAddress: undefined
}
..... many same errors ......
```

**Comment by korniychuk** [comment]
Thank you @Kikobeats ! I added some comments to the PR.

**Comment by korniychuk** [comment]
Also, some more links to the thread:
https://github.com/JoshGlazebrook/socks/issues/23#issuecomment-952790344
https://github.com/delvedor/hpagent/issues/32
