### ISSUE TITLE
DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066

### ISSUE THREAD

**Issue by Kikobeats** [TooTallNate/node-socks-proxy-agent#63]
At Node.js 16:

```
DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
    at Object.connect (_tls_wrap.js:1629:15)
    at SocksProxyAgent.<anonymous> (/home/node/app/node_modules/socks-proxy-agent/src/agent.ts:175:15)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/app/node_modules/socks-proxy-agent/dist/agent.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Pointing to https://github.com/TooTallNate/node-socks-proxy-agent/blob/d1cb60f45bcdc2bef8dbe374d5d3972beaed74e4/src/agent.ts#L175

**Comment by jumoog** [comment]
same issue like #62

**Comment by jumoog** [comment]
https://nodejs.org/api/deprecations.html#deprecations_dep0123_setting_the_tls_servername_to_an_ip_address
